// Generates the two files the app needs eagerly or near-eagerly, from the
// chapter modules that are the source of truth:
//
//   src/data/manifest.ts — what the home screen needs: chapter titles, icons,
//                          groups and word ids. Small enough to always ship.
//   src/data/lexicon.ts  — English word to Spanish, for tapping a word in a
//                          sentence. Loaded with an exercise, not before.
//
//   npm run index
//
// A test compares both against the chapters, so a stale file fails the run.

import { writeFileSync } from 'node:fs'
import { CHAPTERS, ALL_WORDS } from '../src/data/index.ts'
import { GLOSSARY } from '../src/data/glossary.ts'

/** Which module each chapter lives in, so the loader can fetch just that one. */
const MODULES = {
  'adjectives': (await import('../src/data/chapters/adjectives.ts')).ADJECTIVE_CHAPTERS,
  'animals': (await import('../src/data/chapters/animals.ts')).ANIMAL_CHAPTERS,
  'basics': (await import('../src/data/chapters/basics.ts')).BASICS_CHAPTERS,
  'body': (await import('../src/data/chapters/body.ts')).BODY_CHAPTERS,
  'food': (await import('../src/data/chapters/food.ts')).FOOD_CHAPTERS,
  'grammar': (await import('../src/data/chapters/grammar.ts')).GRAMMAR_CHAPTERS,
  'home': (await import('../src/data/chapters/home.ts')).HOME_CHAPTERS,
  'idioms': (await import('../src/data/chapters/idioms.ts')).IDIOM_CHAPTERS,
  'idioms-2': (await import('../src/data/chapters/idioms-2.ts')).IDIOM_CHAPTERS_2,
  'irregular-verbs': (await import('../src/data/chapters/irregular-verbs.ts')).IRREGULAR_VERB_CHAPTERS,
  'irregular-verbs-2': (await import('../src/data/chapters/irregular-verbs-2.ts')).IRREGULAR_VERB_CHAPTERS_2,
  'life': (await import('../src/data/chapters/life.ts')).LIFE_CHAPTERS,
  'phrasal-verbs': (await import('../src/data/chapters/phrasal-verbs.ts')).PHRASAL_VERB_CHAPTERS,
  'phrasal-verbs-2': (await import('../src/data/chapters/phrasal-verbs-2.ts')).PHRASAL_VERB_CHAPTERS_2,
  'regular-verbs': (await import('../src/data/chapters/regular-verbs.ts')).REGULAR_VERB_CHAPTERS,
  'work': (await import('../src/data/chapters/work.ts')).WORK_CHAPTERS,
  'world': (await import('../src/data/chapters/world.ts')).WORLD_CHAPTERS,
}

const sourceOf = new Map()
for (const [file, chapters] of Object.entries(MODULES)) {
  for (const chapter of chapters) sourceOf.set(chapter.id, file)
}

const quote = (text) => `'${text.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`

const manifest = `// Generated by scripts/build-index.mjs — do not edit by hand.
import type { ChapterSummary } from './summary'

export const CHAPTER_INDEX: ChapterSummary[] = [
${CHAPTERS.map(
  (chapter) =>
    `  { id: ${quote(chapter.id)}, title: ${quote(chapter.title)}, icon: ${quote(chapter.icon)}, group: ${quote(chapter.group)}, source: ${quote(sourceOf.get(chapter.id))}, wordIds: [${chapter.words.map((word) => quote(word.id)).join(', ')}] },`,
).join('\n')}
]

export const TOTAL_WORDS = ${ALL_WORDS.length}
`

/** Only single-word entries: a phrase's translation belongs to the phrase. */
const lexicon = new Map()
for (const word of ALL_WORDS) {
  if (/\s/.test(word.word)) continue
  const key = word.word.toLowerCase()
  if (!lexicon.has(key)) lexicon.set(key, word.translation)
  for (const form of word.forms ?? []) {
    const formKey = form.toLowerCase()
    if (!lexicon.has(formKey)) lexicon.set(formKey, word.translation)
  }
}
for (const [key, value] of Object.entries(GLOSSARY)) {
  if (!lexicon.has(key)) lexicon.set(key, value)
}

const lexiconFile = `// Generated by scripts/build-index.mjs — do not edit by hand.
// Vocabulary first, then the glossary, so a word studied as an entry shows the
// sense it was studied in.

export const LEXICON: Record<string, string> = {
${[...lexicon]
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([key, value]) => `  ${/^[a-z][a-z0-9]*$/.test(key) ? key : quote(key)}: ${quote(value)},`)
  .join('\n')}
}
`

writeFileSync('src/data/manifest.ts', manifest)
writeFileSync('src/data/lexicon.ts', lexiconFile)
console.log(`manifest: ${CHAPTERS.length} chapters, ${ALL_WORDS.length} words`)
console.log(`lexicon:  ${lexicon.size} words`)
